// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function App(Props) {
  var greeting = Props.greeting;
  return React.createElement("div", undefined, greeting);
}

var make = App;

exports.make = make;
/* react Not a pure module */
