// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Podcast(Props) {
  Props.podcast;
  return React.createElement("div", undefined, React.createElement("p", undefined, "dog"));
}

var make = Podcast;

exports.make = make;
/* react Not a pure module */
